owner: wdes
repo: status

user-agent: Wdes status (https://github.com/wdes/status)
robotsText: "User-agent: *\n Disallow: /"
assignees:
  - williamdes

sites:
  - name: Wdes FR
    url: https://wdes.fr
    expectedStatusCodes:
      - 200
  - name: Wdes EU
    url: https://wdes.eu
    expectedStatusCodes:
      - 301
  - name: Google 204
    url: https://google.com/generate_204
    expectedStatusCodes:
      - 204
  - name: DC4 server
    url: $DC4_SERVER_URL
    expectedStatusCodes:
      - 200
  - name: Sn-bretagne
    url: https://sn-bretagne.net/liens
    expectedStatusCodes:
      - 200
  - name: DC2 server
    url: $DC2_SERVER_URL
    expectedStatusCodes:
      - 200
  - name: Bitwarden Rust (vaultwarden)
    url: $BITWARDEN_CLOUD
    expectedStatusCodes:
      - 200
  - name: phpMyAdmin sentry instance
    url: $PHPMYADMIN_SENTRY
    expectedStatusCodes:
      - 200
  - name: phpMyAdmin error reports
    url: https://reports.phpmyadmin.net/robots.txt
    expectedStatusCodes:
      - 200
  - name: Williamdes's website
    url: https://williamdes.eu
    expectedStatusCodes:
      - 200
  - name: Williamdes's blog
    url: https://blog.williamdes.eu
    expectedStatusCodes:
      - 200
  - name: Corentin's website
    url: https://corentin.wdes.fr
    expectedStatusCodes:
      - 200

status-website:
  cname: status.datacenters.network
  logoUrl: https://wdes.fr/logo.svg
  name: Datacenters network
  introTitle: "**datacenters.network** is a domain of the Wdes company"
  introMessage: My status page uses **real-time** data from our [GitHub repository](https://github.com/wdes/status). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime#readme)
  navbar:
    - title: Status
      href: /
    - title: GitHub config
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  # https://crontab.guru/#0_0_*_*_*
  graphs: "0 0 * * *"
  # https://crontab.guru/#*/30_*_*_*_*
  responseTime: "*/30 * * * *"
  # https://crontab.guru/#0_*_*_*_*
  staticSite: "0 * * * *"
  # https://crontab.guru/#0_0_*_*_*
  summary: "0 0 * * *"
  # https://crontab.guru/#0_0_*_*_*
  updateTemplate: "0 0 * * *"
  # https://crontab.guru/#0_3_*_*_*
  updates: "0 3 * * *"
  # https://crontab.guru/#*/5_*_*_*_*
  uptime: "*/5 * * * *"

commitMessages:
  commitAuthorName: "Wdes Bot"
  commitAuthorEmail: "wdes-bot@users.noreply.github.com"
  readmeContent: "Update summary in README [skip ci] [upptime]"
  summaryJson: "Update status summary [skip ci] [upptime]"
  graphsUpdate: "Update graphs [skip ci] [upptime]"
