owner: wdes
repo: status

user-agent: Wdes status (https://github.com/wdes/status)
robotsText: "User-agent: *\n Disallow: /"
assignees:
  - williamdes

sites:
  - name: Wdes FR
    url: https://wdes.fr
  - name: Wdes EU
    url: https://wdes.eu
  - name: Google 204
    url: https://google.com/generate_204
    expectedStatusCodes:
      - 204
  - name: DC4 server
    url: $DC4_SERVER_URL
    expectedStatusCodes:
      - 403
  - name: Williamdes's website
    url: https://william.wdes.fr
  - name: Corentin's website
    url: https://corentin.wdes.fr

status-website:
  cname: status.datacenters.network
  logoUrl: https://wdes.fr/logo.svg
  name: Datacenters network
  introTitle: "**datacenters.network** is a domain of the Wdes company"
  introMessage: My status page uses **real-time** data from our [GitHub repository](https://github.com/wdes/status). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime#readme)
  navbar:
    - title: Status
      href: /
    - title: GitHub config
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "Wdes Bot"
  commitAuthorEmail: "wdes-bot@users.noreply.github.com"
  readmeContent: "Update summary in README [skip ci] [upptime]"
  summaryJson: "Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: "Update graphs [skip ci] [upptime]"
